name: wydatki
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2
  flutterfire_ui: ^0.3.1
  intl: ^0.17.0
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  json_annotation: ^4.6.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  dio: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^1.1.1
  analyzer: ^3.0.0
  injectable_generator: ^1.5.3
  bloc_test: ^9.1.0
  mocktail: ^0.3.0


flutter:
  uses-material-design: true
